name: coshion
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  # flutter_native_splash: ^2.3.9
  another_flutter_splash_screen: ^1.2.0
  phone_form_field: ^8.1.1
  intl_phone_field: ^3.2.0
  convex_bottom_bar: ^3.2.0
  firebase_core: ^2.24.2
  otp_text_field: ^1.1.3
  firebase_auth: ^4.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/
  uses-material-design: true
