// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw0nCOFMUM2kUUBCHtPIT_-leEYvv_E84',
    appId: '1:1008469404042:web:08ef2b4bfc06a585040073',
    messagingSenderId: '1008469404042',
    projectId: 'coshion-101ac',
    authDomain: 'coshion-101ac.firebaseapp.com',
    storageBucket: 'coshion-101ac.appspot.com',
    measurementId: 'G-CWD5SYLVPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQY4BjzRLV40ABpz50uvNJzlAS2TJolvs',
    appId: '1:1008469404042:android:95e6f83c8382884c040073',
    messagingSenderId: '1008469404042',
    projectId: 'coshion-101ac',
    storageBucket: 'coshion-101ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlvj0xr3AptgJYoeKs2QUhMh7_Cnv75ps',
    appId: '1:1008469404042:ios:fefd07210a69f8b5040073',
    messagingSenderId: '1008469404042',
    projectId: 'coshion-101ac',
    storageBucket: 'coshion-101ac.appspot.com',
    iosBundleId: 'com.coshion.coshion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlvj0xr3AptgJYoeKs2QUhMh7_Cnv75ps',
    appId: '1:1008469404042:ios:9783b1a85d90b514040073',
    messagingSenderId: '1008469404042',
    projectId: 'coshion-101ac',
    storageBucket: 'coshion-101ac.appspot.com',
    iosBundleId: 'com.coshion.coshion.RunnerTests',
  );
}
